bucket_name              = "loan-optimization-execution-bucket"
environment              = "development"
admin_role_name          = "amplify-d2k5uxsf6lu8a3-ma-amplifyAuthadminGroupRole-e2bKlmBSxySA"
auth_role_name           = "amplify-d2k5uxsf6lu8a3-ma-amplifyAuthauthenticatedU-tqJl48ukxMIk"
unauth_role_name         = "amplify-d2k5uxsf6lu8a3-ma-amplifyAuthunauthenticate-cqO87wbRQuhi"